# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artwork',
            field=models.ImageField(blank=True, default=b'default_artwork', null=True, upload_to=b'artworks'),
        ),
    ]
