# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20170401_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
