# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_auto_20170410_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artwork',
            field=models.ImageField(blank=True, default=b'media/artworks/default_artwork.png', null=True, upload_to=b'artworks'),
        ),
    ]
