# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_auto_20170410_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artwork',
            field=models.ImageField(upload_to=b'artworks'),
        ),
    ]
